### ISSUE TITLE
-U, -H suffix and Avg. Rank in Table 2

### ISSUE THREAD

**Issue by LostXine** [kennymckormick/TransRank#1]
Hello,

Thank you for your great work. 
Could you explain the difference between  Sync-U and Sync-H in Table 2, and similarly, Order-U and Order-H?
At the same time, may I assume that Avg. Rank is the rank of the ground truth given by the model prediction?
Sorry if I missed any of your descriptions in your paper.

Thanks!

**Comment by kennymckormick** [comment]
Hi, LostXine, 
-U, -H just denotes the dataset (UC101 or HMDB51). Besides Avg.Rank means the average ranking on 5 temporal tasks (we have four algorithms, if one algorithm performs the best on one task, the corresponding rank is 1; if worst, the rank is 4).

**Comment by LostXine** [comment]
I see. Thank you so much.
